export { default as Page } from './Page'
export { default as DevInfo } from './DevInfo'
export { default as Skill } from './Skill'
export { default as Skills } from './Skills'
export { default as DevWork } from './DevWork'
export { default as DevExpTimeline } from './DevExpTimeline'
export { default as DevEduTimeline } from './DevEduTimeline'
export {default as ShowProjects} from './ShowProjects'
export {default as CommentsSlider} from './CommentsSlider'
export {default as ContactForm} from './ContactForm'